apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appOfApps.name }}
  namespace: {{ .Values.appOfApps.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: {{ .Values.appOfApps.project }}
  source:
    repoURL: {{ .Values.appOfApps.repoURL }}
    targetRevision: {{ .Values.appOfApps.targetRevision }}
    path: {{ .Values.appOfApps.path }}
  destination:
    server: {{ .Values.appOfApps.destinationServer }}
    namespace: {{ .Values.appOfApps.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
