---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: catalog-db-es
  namespace: catalog
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: catalog-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: stage-retail-store-catalog-db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: stage-retail-store-catalog-db-credentials
        property: password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orders-db-es
  namespace: orders
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: orders-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: stage-retail-store-orders-db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: stage-retail-store-orders-db-credentials
        property: password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orders-rabbitmq-es
  namespace: orders
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: orders-rabbitmq
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: stage-retail-store-mq-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: stage-retail-store-mq-credentials
        property: password
