name: Build Image with tag
run-name : Build and Tag ${{ github.event.inputs.service }} with ${{ github.event.inputs.version_type }} bump

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to build'
        required: true
        type: choice
        options:
          - ui
          - catalog
          - cart
          - orders
          - checkout
      version_type:
        description: 'Level of version bump'
        required: true
        type: choice
        default: patch
        options:
          - major
          - minor
          - patch

concurrency:
  group: tag-update
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Calculate New Version
        id: version
        run: |
          current_version=$(yq e ".${{ inputs.service }}.tag" versions.yaml)
          IFS='.' read -r major minor patch <<< "$current_version"
          
          case "${{ inputs.version_type }}" in
            major) new_version="$((major + 1)).0.0" ;;
            minor) new_version="$major.$((minor + 1)).0" ;;
            patch) new_version="$major.$minor.$((patch + 1))" ;;
          esac
          
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
          role-session-name: TagServiceBuild

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ inputs.service }}
          IMAGE_TAG: ${{ steps.version.outputs.new_version }}
        run: |
          IMAGE_URI="$REGISTRY/$REPOSITORY:$IMAGE_TAG"
          
          echo "Building service: $REPOSITORY with tag: $IMAGE_TAG"
          
          buildah build \
            -f src/$REPOSITORY/Dockerfile \
            --layers \
            --cache-from $REGISTRY/$REPOSITORY \
            --cache-to $REGISTRY/$REPOSITORY \
            -t $IMAGE_URI \
            src/$REPOSITORY
          
          buildah push $IMAGE_URI

      - name: Update versions.yaml
        run: |
          yq e ".${{ inputs.service }}.tag = \"${{ steps.version.outputs.new_version }}\"" -i versions.yaml

      - name: Commit and Push version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add versions.yaml
          git commit -m "Bump ${{ inputs.service }} (${{ inputs.version_type }}) to ${{ steps.version.outputs.new_version }}"
          git push