name: Build services on main

on:
  push:
    branches:
      - "main"

jobs:
  changes:
    uses: ./.github/workflows/changes.yaml

  build:
    name: Build
    needs: changes
    if: needs.changes.outputs.has_changes == 'true'
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read      
    strategy:
      matrix: ${{ fromJson(needs.changes.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
          role-session-name: MainBranchBuild

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ matrix.service }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI="$REGISTRY/$REPOSITORY:$IMAGE_TAG"
          
          echo "Building service: ${{ matrix.service }}"
          
          buildah build \
            -f src/${{ matrix.service }}/Dockerfile \
            --layers \
            --cache-from $REGISTRY/$REPOSITORY \
            --cache-to $REGISTRY/$REPOSITORY \
            -t $IMAGE_URI \
            src/${{ matrix.service }}
          
          buildah push $IMAGE_URI