name: Deploy
run-name: Deploy infrastructure

on:
  workflow_dispatch:
    inputs:
      layer:
        description: 'Layer name to deploy'
        required: true
        type: choice
        default: "all"
        options:
          - bootstrap
          - ops
          - app
          - all
      skip-sentinel:
        description: 'Skip Sentinel policy checks'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  bootstrap:
    name: Deploy bootstrap layer
    if: ${{ inputs.layer == 'bootstrap' || inputs.layer == 'all' }}
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
    with:
      layer: bootstrap
      skip-sentinel: ${{ inputs.skip-sentinel }}

  ops:
    name: Deploy ops layer
    needs: [bootstrap]
    if: ${{ always() && !failure() && !cancelled() && (inputs.layer == 'ops' || inputs.layer == 'all') }}
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
    with:
      layer: ops
      skip-sentinel: ${{ inputs.skip-sentinel }}

  app:
    name: Deploy app layer
    needs: [ops]
    if: ${{ always() && !failure() && !cancelled() && (inputs.layer == 'app' || inputs.layer == 'all') }}
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
    with:
      layer: app
      skip-sentinel: ${{ inputs.skip-sentinel }}
