name: Destroy Infrastructure
run-name: Destroy ${{ inputs.environment }} / ${{ inputs.layer }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy from'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - prod

      layer:
        description: 'Layer to destroy'
        required: true
        default: 'app'
        type: choice
        options:
          - app
          - ops
          - bootstrap

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    env:
      TF_IN_AUTOMATION: true
      TF_VAR_argocd_github_token: ${{ secrets.ARGOCD_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: latest

      - name: Set working directory
        id: workdir
        run: |
          echo "dir=./terraform/live/${{ inputs.environment }}/${{ inputs.layer }}" >> $GITHUB_OUTPUT

      - name: Terragrunt Init
        run: terragrunt init -input=false
        working-directory: ${{ steps.workdir.outputs.dir }}

      - name: Terragrunt Destroy
        working-directory: ${{ steps.workdir.outputs.dir }}
        run: |
          terragrunt destroy -auto-approve -input=false
