name: "Scans"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  write-all: true

jobs:
  scans:
    name: "Comprehensive Scans"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup-env

      - name: Run AI Ops
        uses: ./.github/actions/ai-ops
        with:
          python-version: '3.11'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
