name: Terraform Apply

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment name to apply (stage, prod)'
        required: true
        type: string
      layer:
        description: 'Layer name to apply (bootstrap, ops, app)'
        required: true
        type: string


permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    env:
      TF_IN_AUTOMATION: true
      TF_VAR_argocd_github_token: ${{ secrets.ARGOCD_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: latest

      - name: Set working directory
        id: workdir
        run: |
          if [ "${{ inputs.layer }}" = "bootstrap" ]; then
            echo "dir=./terraform/layers/bootstrap" >> $GITHUB_OUTPUT
          else
            echo "dir=./terraform/layers/${{ inputs.layer }}/${{ inputs.environment }}" >> $GITHUB_OUTPUT
          fi
        working-directory: .

      - uses: actions/download-artifact@v4
        with:
          name: terragrunt-plan-${{ inputs.environment }}-${{ inputs.layer }}
          path: ${{ steps.workdir.outputs.dir }}

      - name: Terragrunt Init
        run: terragrunt init -input=false
        working-directory: ${{ steps.workdir.outputs.dir }}

      - name: Terragrunt Apply
        run: terragrunt apply -input=false $PWD/tfplan
        working-directory: ${{ steps.workdir.outputs.dir }}
