name: Terraform Plan

on:
  workflow_call:
    outputs:
      plan_exitcode:
        description: "The exit code of the terragrunt plan command"
        value: ${{ jobs.plan.outputs.plan_exitcode }}
    inputs:
      environment:
        description: 'Environment name to plan (stage, prod)'
        required: true
        type: string
      layer:
        description: 'Layer name to plan (bootstrap, ops, app)'
        required: true
        type: string


permissions:
  contents: read
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-24.04
    env:
      TF_IN_AUTOMATION: true
      TF_VAR_argocd_github_token: ${{ secrets.ARGOCD_TOKEN }}
    outputs:
      plan_exitcode: ${{ steps.tf_plan.outputs.plan_exitcode }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: latest

      - name: Set working directory
        id: workdir
        run: |
          echo "dir=./terraform/live/${{ inputs.environment }}/${{ inputs.layer }}" >> $GITHUB_OUTPUT
        working-directory: .

      - name: Terragrunt Init
        run: terragrunt init -input=false
        working-directory: ${{ steps.workdir.outputs.dir }}

      - name: Terragrunt Validate
        run: terragrunt validate
        working-directory: ${{ steps.workdir.outputs.dir }}

      - name: Terragrunt Plan
        id: tf_plan
        working-directory: ${{ steps.workdir.outputs.dir }}
        run: |
          set +e

          PLAN_ARGS="-detailed-exitcode -input=false -out=$PWD/tfplan"    

          terragrunt plan $PLAN_ARGS
          exitcode=$?
          echo "plan_exitcode=$exitcode" >> $GITHUB_OUTPUT
          
          # Terragrunt (Terraform plan) -detailed-exitcode returns:
          # 0 = Succeeded, diff is empty (no changes)
          # 1 = Errored
          # 2 = Succeeded, there is a diff
          if [ $exitcode -eq 1 ]; then
            exit 1
          fi
          terragrunt show -no-color $PWD/tfplan > $PWD/tfplan.txt

      - name: Archive plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terragrunt-plan-${{ inputs.environment }}-${{ inputs.layer }}
          path: |
            ${{ steps.workdir.outputs.dir }}/tfplan
            ${{ steps.workdir.outputs.dir }}/tfplan.txt
